apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure
spec:
  selector:
    matchLabels:
      app: azure
  replicas: 2
  template:
    metadata:
      labels:
        app: azure
    spec :
      imagePullSecrets:
        - name: azuresecret
      containers:
      - name: azure
        image: registry3247.azurecr.io/azure:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: azureservice
  labels:
    app: azure
spec:
  type: LoadBalancer
  selector:
    app: azure
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 443
    name: https
